# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/test.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/test.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x10proto/test.proto\"\x14\n\x05mytag\x12\x0b\n\x03tag\x18\x01 \x01(\x05\"7\n\x05mymsg\x12\x0b\n\x03len\x18\x01 \x01(\x05\x12\x0c\n\x04type\x18\x02 \x03(\x05\x12\x13\n\x03tag\x18\x03 \x01(\x0b\x32\x06.mytagb\x06proto3'
)




_MYTAG = _descriptor.Descriptor(
  name='mytag',
  full_name='mytag',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tag', full_name='mytag.tag', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=40,
)


_MYMSG = _descriptor.Descriptor(
  name='mymsg',
  full_name='mymsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='len', full_name='mymsg.len', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='mymsg.type', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tag', full_name='mymsg.tag', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=97,
)

_MYMSG.fields_by_name['tag'].message_type = _MYTAG
DESCRIPTOR.message_types_by_name['mytag'] = _MYTAG
DESCRIPTOR.message_types_by_name['mymsg'] = _MYMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

mytag = _reflection.GeneratedProtocolMessageType('mytag', (_message.Message,), {
  'DESCRIPTOR' : _MYTAG,
  '__module__' : 'proto.test_pb2'
  # @@protoc_insertion_point(class_scope:mytag)
  })
_sym_db.RegisterMessage(mytag)

mymsg = _reflection.GeneratedProtocolMessageType('mymsg', (_message.Message,), {
  'DESCRIPTOR' : _MYMSG,
  '__module__' : 'proto.test_pb2'
  # @@protoc_insertion_point(class_scope:mymsg)
  })
_sym_db.RegisterMessage(mymsg)


# @@protoc_insertion_point(module_scope)
